train:
  batch_size: 128
  learning_rate: 0.01
  epochs: 1000
  sample_epoch: 1
  sample_scramble_count: 20
  sample_cube_count: 100
  buffer_size: 10000
  temperature: 0.3
  validation_epoch: 10
  video_path: ./video
  model_path: ./pretrained
  progress_path: ./train_progress
validation:
  max_timesteps: 200
  sample_scramble_count: 20
  sample_cube_count: 5
env:
  cube_size: 2
model:
  hidden_dim:
    - 256
    - 64
    - 32
device: cpu