train:
  batch_size: 1024
  sample_size: 10000
  learning_rate: 0.00005
  epochs: 100000
  sample_epoch: 1
  sample_scramble_count: 30
  sample_cube_count: 200
  buffer_size: 20000
  temperature: 1.0
  validation_epoch: 500
  num_processes: 14
  video_path: ./video
  model_path: ./pretrained
  progress_path: ./train_progress
validation:
  max_timesteps: 200
  sample_scramble_count: 30
  sample_cube_count: 10
env:
  cube_size: 3
model:
  hidden_dim:
    - 1024
    - 256
    - 128
device: cpu
mcts:
  numMCTSSim: 50
  cpuct: 1.0
  virtual_loss_const: 150
  value_min: -10.0
test:
  cube_size: 3
  test_model_path: './pretrained'
  save_file_path: './test'
  max_timesteps: 200
  show_scramble_count: 100
  masks: 'x' # ['x', 'both', 'only']
  mcts_: 'only' # ['x', 'both', 'only']
