train:
  batch_size: 256
  sample_size: 1000
  learning_rate: 0.001
  epochs: 10
  sample_epoch: 1
  sample_scramble_count: 5
  sample_cube_count: 50
  buffer_size: 20000
  temperature: 0.7
  validation_epoch: 10
  video_path: ./video
  model_path: ./pretrained
  progress_path: ./train_progress
validation:
  max_timesteps: 30
  sample_scramble_count: 3
  sample_cube_count: 10
env:
  cube_size: 3
model:
  hidden_dim:
    - 256
    - 64
    - 32
device: cuda
mcts:
  numMCTSSim: 10
  cpuct: 1.0
test:
  cube_size: 2
  test_model_path: './test/model'
  save_file_path: './test'
  max_timesteps: 200
  show_scramble_count: 100
  masks: 'both' #'only' # or 'both'