train:
  batch_size: 256
  sample_size: 1000
  learning_rate: 0.001
  epochs: 1000
  sample_epoch: 1
  sample_scramble_count: 30
  sample_cube_count: 100
  buffer_size: 50000
  temperature: 0.3
  validation_epoch: 100
  video_path: ./video
  model_path: ./pretrained/quarter_model
  progress_path: ./train_progress/quarter_model
validation:
  max_timesteps: 100
  sample_scramble_count: 30
  sample_cube_count: 10
env:
  cube_size: 2
model:
  hidden_dim:
    - 64
    - 16
    - 8
device: cpu
mcts:
  numMCTSSim: 10
  cpuct: 1.0