train:
  batch_size: 256
  sample_size: 1000
  learning_rate: 0.001
  epochs: 1000
  sample_epoch: 1
  sample_scramble_count: 30
  sample_cube_count: 100
  buffer_size: 50000
  temperature: 0.0
  validation_epoch: 100
  video_path: ./video
  model_path: ./pretrained/temperature_10
  progress_path: ./train_progress/temperature_10
validation:
  max_timesteps: 100
  sample_scramble_count: 30
  sample_cube_count: 10
env:
  cube_size: 2
model:
  hidden_dim:
    - 256
    - 64
    - 32
device: cpu
mcts:
  numMCTSSim: 10
  cpuct: 1.0